Mafia_Tournaments/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_view
from team_interactions import views as team_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls")),
    path('register/', users_view.register, name='register'),
    path('profile/', include("users.urls")),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('contract/', team_view.get_contract, name='contract'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile'),
    path('teams_management/', views.team_management, name='team_management'),
    path('my_contracts/', views.my_contracts, name='my_contracts'),
    path('my_team/', views.my_team, name='my_team'),
]

team_interactions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Team(models.Model):
    league_CHOICES = (
        (1, 'Высшая лига'),
        (2, 'Вторая лига'),
        (3, 'Третья лига'),
    )
    creation_date = models.DateTimeField("Creation date",auto_now_add=True,blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')
    league = models.PositiveSmallIntegerField(choices=league_CHOICES, default=3)
    name = models.CharField(max_length=256)
    description = models.TextField()
    can_play = models.BooleanField(default=False)
    active_players = models.PositiveIntegerField(default=0)
    logo = models.ImageField(upload_to ='static/team_logo/', max_length=100)
    team_value = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def change_team_value(self, change_value):
        self.team_value += change_value
        self.save()

    def check_can_play(self):
        if self.active_players >= 4 and self.active_players <= 6 :
            self.can_play = True
        else:
            self.can_play = False
        self.save()

    def change_active(self, change_value):
        self.active_players += change_value
        self.check_can_play()
        self.save()

class Contract(models.Model):
    status_choices = ((1, 'Рассматривается игроком'), (2, 'Рассматривается владельцем'), (3, "Принят"), (4, "Отклонен"), (5, "Запрос на расторжение владельцем"),
                      (6, "Запрос на расторжение игроком"), (7, 'Расторгнут'))
    player = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contract_player')
    team_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contract_team_owner')
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    duration = models.IntegerField(default=2)
    salary = models.PositiveIntegerField(default=200)
    contract_value = models.IntegerField(default=0)
    contract_status = models.PositiveSmallIntegerField(choices=status_choices, default=1)
    contract_cancel_proof = models.TextField(max_length=3000, default='')
    played_game_bonus = models.IntegerField(default=0)
    victory_coef = models.IntegerField(default=0)

    def __str__(self):
        return self.player.username

    def change_status(self, new_status):
        self.contract_status = new_status
        self.save()

    def get_income_transitions(self):
        if self.contract_status == 1:
            return [(4,'Отклонить')]
        elif self.contract_status == 2:
            return [(3,'Принять'), (4,'Отклонить')]
        elif self.contract_status == 3:
            return [(5,'Расторгнуть(влд)')]

    def get_outcome_transitions(self):
        if self.contract_status == 1:
            return [(3,'Принять'), (4,'Отклонить')]
        elif self.contract_status == 2:
            return [(4,'Отклонить')]
        elif self.contract_status == 3:
            return [(6,'Расторгнуть(игр)')]

    @staticmethod
    def post_save(sender, **kwargs):
        instance = kwargs.get('instance')
        if instance.contract_status == 7:
            instance.player.userprofile.revoke_contract()
            team = Team.objects.get(name=instance.team)
            team.change_team_value(-instance.contract_value)

post_save.connect(Contract.post_save, sender=Contract)

users/models.py
from django.db import models
from django.contrib.auth.models import User,Group
from team_interactions.models import Team, Contract
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    leagues = ((1, "Имеет допуск к высшей лиге"), (2, "Имеет допуск ко второй лиге"), (3, "Имеет допуск к третьей лиге"))
    access = models.PositiveSmallIntegerField(choices=leagues, default=3)
    in_team = models.BooleanField(default=False)
    in_reserve = models.BooleanField(default=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True )
    def __str__(self):
        return self.user.username

    def change_reserve_state(self):
        self.in_reserve = not self.in_reserve
        if self.in_reserve:
            self.team.change_active(-1)
        else:
            self.team.change_active(+1)
        self.save()

    def signup_contract(self, contract):
        self.in_team = True
        self.team = contract.team
        self.save()

    def revoke_contract(self):
        print('contract was revoked for player ' + str(self.user.username))
        self.in_team = False
        self.team = None
        self.save()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

class TMProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    cup_list = ((1, "Золотой кубок"), (2, "Серебряный кубок"), (3, "Нет кубка"))
    cups = models.PositiveSmallIntegerField(choices=cup_list, default=3)
    access_to_admin = models.BooleanField(default=True)
    status = models.CharField(max_length=256, default='Turnir master')
    comment = models.CharField(max_length=256, default='pidor')
    def __str__(self):
        return self.user.username

@receiver(post_save, sender = TMProfile)
def create_TM_user_profile(sender, instance, created, **kwargs):
    if created:
        group = instance.group
        instance.user.groups.add(group)
        instance.user.is_staff=instance.access_to_admin
        instance.user.save()

@receiver(post_delete, sender = TMProfile)
def create_TM_user_profile(sender, instance, **kwargs):
    group = instance.group
    instance.user.groups.clear()
    instance.user.is_staff=False
    instance.user.save()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
from .models import UserProfile
from team_interactions.contract_utils import *

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {'form' : form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def team_management(request):
    if request.user.is_authenticated:
        my_teams = Team.objects.filter(owner=request.user)
        if request.method == 'POST':
            usr = request.POST.get('player')
            usr_obj = UserProfile.objects.filter(user=usr)[:1].get()
            usr_obj.change_reserve_state()
        context = {'my_teams': my_teams}
    return render(request, 'users/profile_my_owned_teams.html', context)

@login_required
def my_contracts(request):
    outcome_contracts = Contract.objects.filter(player=request.user)
    income_contracts = Contract.objects.filter(team_owner=request.user)
    if request.method == 'POST':
        if request.POST.get('outgoing'):
            process_outcome_contract_request(request, outcome_contracts)
        elif request.POST.get('incoming'):
            process_income_contract_request(request, income_contracts)
    context = {'team_enroll_contract': outcome_contracts, 'team_request_contract': income_contracts}
    return render(request, 'users/profile_my_contracts.html', context)

@login_required
def my_team(request):
    if request.user.is_authenticated:
        player = UserProfile.objects.filter(user=request.user)[:1].get()
        players_in_team = UserProfile.objects.filter(team=player.team)
        context = {'team':player.team,'players_in_team': players_in_team}
    return render(request, 'users/profile_my_team.html', context)

templates/users/login.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Вход
{% endblock %}
{% block content %}
        <div class="content-section">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <legend class="border-bottom mb-4"> Войти</legend>
                            {{ form|crispy }}
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit"> Войти</button>
                        </div>
                    </form>
                <div class="border-top pt-3">
                    <small>Еще не с нами?<a class="ml-2" href="{% url 'register' %}">Зарегистритуйтесь</a></small>
                </div>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
{% endblock %}

templates/users/logout.html
{% extends 'landing/base.html' %}
{% block title %}
    Выход
{% endblock %}
{% block content %}
    <div class="content-section">
    <div class="row justify-content-center">
        <div class = "col-3"></div>
        <div class = "col-6" align="center">
            <div class="border-top pt-3">
                <h2>Вы вышли</h2>
            </div>
            <div class="border-top pt-3">
                <small>Может хотите назад?<a class="ml-2" href="{% url 'login' %}">Войти</a></small>
            </div>
        </div>
        <div class = "col-3"></div>

    </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'landing/base.html' %}
{% block title %}
    Профиль
{% endblock %}
{% block content %}
<div class="row justify-content-center">

    <h1>{{ user.username }}</h1>
</div>
{% endblock %}

templates/users/profile_my_contracts.html
{% extends 'landing/base.html' %}

{% block title %}
    Мои контракты
<style>
.overlay {
  position: fixed;
  display: none;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0,0,0,0.5);
  z-index: 2;
  cursor: pointer;
}

.reason{
  position: absolute;
  top: 50%;
  left: 50%;
  color: white;
  transform: translate(-50%,-50%);
  -ms-transform: translate(-50%,-50%);
}
</style>
{% endblock %}
{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
    <thead>
        <tr>  <td colspan="100%" style="text-align: center; background-color: cornflowerblue"> Ваши заявки на прием в команду </td>  </tr>
        <tr>
            <th>Команда</th>
            <th>Лига</th>
            <th>Владелец</th>
            <th>Длительность</th>
            <th>Зарплата</th>
            <th>Стоимость контракта</th>
            <th>Статус контракта</th>
            <th>Управление контрактом</th>
        </tr>
    </thead>
    {% for contract in team_enroll_contract %}
        <tr>
            <td> {{contract.team.name}} </td>
            <td> {{contract.team.league}} </td>
            <td> {{contract.team_owner}} </td>
            <td> {{contract.duration}} </td>
            <td> {{contract.salary}} </td>
            <td> {{contract.contract_value}} </td>
            <td> {{contract.get_contract_status_display}} </td>
            <td>
                <form method="post">
                    {% csrf_token %}
                    {% for transition in contract.get_outcome_transitions %}
                    {% if transition.0 == 6%}
                        <button class="btn btn-primary" type="button" onclick="on( 'o_{{forloop.counter}}' )"> {{transition.1}} </button>
                        <div class="overlay" id="o_{{forloop.counter}}">
                            <div class="reason">
                                Введите причину разрыва(строчку оплаты неустойки):<br>
                                <input type="text" name="reason" value="">
                                <button class="btn btn-primary" name="outgoing" type="submit" value="{{transition.0}}"> Подтвердить </button>
                            </div>
                        </div>
                    {% else %}
                        <button class="btn btn-primary" name="outgoing" type="submit" value="{{transition.0}}"> {{transition.1}} </button>
                    {% endif %}

                    {% endfor %}
                    <input type="hidden" name="contract" value="{{contract.id}}" />
                </form>
            </td>
        </tr>
    {% endfor %}
    </table>
</div>
<div class="table-responsive">
    <table class="table table-striped">
    <thead>
        <tr>  <td colspan="100%" style="text-align: center; background-color: cornflowerblue"> Заявки на прием в вашу команду </td>  </tr>
        <tr>
            <th>Команда</th>
            <th>Лига</th>
            <th>Игрок</th>
            <th>Длительность</th>
            <th>Зарплата</th>
            <th>Стоимость контракта</th>
            <th>Статус контракта</th>
            <th>Управление контрактом</th>
        </tr>
    </thead>
    {% for contract in team_request_contract %}
        <tr>
            <td> {{contract.team.name}} </td>
            <td> {{contract.team.league}} </td>
            <td> {{contract.player.username}} </td>
            <td> {{contract.duration}} </td>
            <td> {{contract.salary}} </td>
            <td> {{contract.contract_value}} </td>
            <td> {{contract.get_contract_status_display}} </td>
            <td>
                <form method="post">
                    {% csrf_token %}
                    {% for transition in contract.get_income_transitions %}
                    {% if transition.0 == 5%}
                        <button class="btn btn-primary" type="button" onclick="on( 'i_{{forloop.counter}}' )"> {{transition.1}} </button>
                        <div class="overlay" id="i_{{forloop.counter}}">
                            <div class="reason">
                                Введите причину разрыва(строчку оплаты неустойки):<br>
                                <input type="text" name="reason" value="">
                                <button class="btn btn-primary" name="incoming" type="submit" value="{{ transition.0 }}"> Подтвердить </button>
                            </div>
                        </div>
                    {% else %}
                        <button class="btn btn-primary" name="incoming" type="submit" value="{{ transition.0 }}" > {{transition.1}} </button>
                    {% endif %}

                    {% endfor %}
                    <input type="hidden" name="contract" value="{{contract.id}}" />
                </form>
            </td>
        </tr>
    {% endfor %}
    </table>
</div>

<script type="text/javascript">
 function on(x) {
 console.log(x);
  document.getElementById(x).style.display = "block";
}

</script>
{% endblock %}

templates/users/profile_my_owned_teams.html
{% extends 'landing/base.html' %}
{% block title %}
    Управление моими командами
{% endblock %}
{% block content %}
<div class="table-responsive">
<table class="table table-striped">
    <thead>
        <tr>  <td colspan="100%" style="text-align: center; background-color: cornflowerblue"> Команды под моим управлением</td>  </tr>
        <tr>
            <th>Команда</th>
            <th>Лига</th>
            <th>Команда может играть</th>
            <th>Состав(Активен)</th>
        </tr>
    </thead>
    {% for team in my_teams %}
        <tr>
            <td> {{team.name}} </td>
            <td> {{team.league}} </td>
            <td> {{team.can_play|yesno:"Да,Нет"}} </td>
            <td>
                {% if team.userprofile_set.all %}
                    {% for usr in team.userprofile_set.all %}
                        <form style='float:left;' method="post">
                            {{ usr.user.username }}
                            {% csrf_token %}
                            <button class="btn btn-primary" type="submit" title="{{usr.in_reserve|yesno:'Нажмите чтобы перевести в основной состав,Нажмите чтобы перевести в резерв'}}">
                                {% if usr.in_reserve%}
                                <span><i class="fa fa-toggle-off"></i></span>
                                {% else %}
                                <span><i class="fa fa-toggle-on"></i></span>
                                {% endif %}
                            </button>
                            <input type="hidden" name="player" value="{{usr.user.id}}" />
                        <span> &nbsp; </span>
                        </form>
                    {% endfor %}
                {% endif %}
            </td>

        </tr>
    {% endfor %}
    </table>
</div>
{% endblock %}

templates/users/profile_my_team.html
{% extends 'landing/base.html' %}
{% block title %}
    Моя команда
{% endblock %}
{% block content %}
<div class="table-responsive">
<table class="table table-striped">
    <thead>
        <tr>  <td colspan="100%" style="text-align: center; background-color: cornflowerblue"> Состав команды "{{team}}"</td>  </tr>
        <tr>
            <th>Игрок</th>
            <th >Активен <i title="Игрок в основном составе" class="fa fa-info-circle"></i></th>
            <th>Допуск</th>
        </tr>
    </thead>
    {% for player in players_in_team %}
        <tr>
            <td> {{player.user.username}} </td>
            <td > {{player.in_reserve|yesno:"Нет,Да"}} </td>
            <td> {{player.access}} </td>
        </tr>
    {% endfor %}
    </table>
</div>
{% endblock %}

templates/users/register.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Регистрация
{% endblock %}
{% block content %}
        <div class="content-section">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4"> Присоединяйтесь к нам, у нас есть печеньки</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit"> Зарегистрироваться</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small>Уже есть профиль?<a class="ml-2" href="{% url 'login' %}">Войти </a></small>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
        </div>
{% endblock %}